// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsp156Pq3C2bc4tXUmGgB1cyVGo5GqWOo',
    appId: '1:955500407963:web:115f80d63ece14b2862a3e',
    messagingSenderId: '955500407963',
    projectId: 'vize030718058-a5c27',
    authDomain: 'vize030718058-a5c27.firebaseapp.com',
    storageBucket: 'vize030718058-a5c27.appspot.com',
    measurementId: 'G-V7EPSJKYNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhuEPcH0H6wbEtAAGj2c6LPWsy2fCgQpc',
    appId: '1:955500407963:android:5f8c7627ae36ce6c862a3e',
    messagingSenderId: '955500407963',
    projectId: 'vize030718058-a5c27',
    storageBucket: 'vize030718058-a5c27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTvz74JQyqfvqGjBwMzphoDxSD63IKZY',
    appId: '1:955500407963:ios:cbb6824421c76dde862a3e',
    messagingSenderId: '955500407963',
    projectId: 'vize030718058-a5c27',
    storageBucket: 'vize030718058-a5c27.appspot.com',
    iosClientId: '955500407963-s6qr449j7ttbgu3e6sd4keghe2cv0amf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHTvz74JQyqfvqGjBwMzphoDxSD63IKZY',
    appId: '1:955500407963:ios:cbb6824421c76dde862a3e',
    messagingSenderId: '955500407963',
    projectId: 'vize030718058-a5c27',
    storageBucket: 'vize030718058-a5c27.appspot.com',
    iosClientId: '955500407963-s6qr449j7ttbgu3e6sd4keghe2cv0amf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
